---
- name: Check mandatory variables
  assert:
    that:
      - distribution is defined
      - release is defined

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ prerequisites[(ansible_os_family | lower)] }}"

- name: Deploy OS-specific
  include: "{{(ansible_os_family | lower)}}.yml"

- name: Start service httpd, if not started
  service:
    name: "{{ httpd_srv[(ansible_os_family | lower)] }}"
    state: started
  when: ansible_virtualization_type != 'docker'
